/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as ApiDecksDeckIdPdfRouteImport } from './routes/api.decks.$deckId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecksDeckIdPdfRoute = ApiDecksDeckIdPdfRouteImport.update({
  id: '/api/decks/$deckId/pdf',
  path: '/api/decks/$deckId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
  '/api/decks/$deckId/pdf': typeof ApiDecksDeckIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks': typeof DecksIndexRoute
  '/api/decks/$deckId/pdf': typeof ApiDecksDeckIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/decks/': typeof DecksIndexRoute
  '/api/decks/$deckId/pdf': typeof ApiDecksDeckIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks/$deckId' | '/decks/' | '/api/decks/$deckId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks/$deckId' | '/decks' | '/api/decks/$deckId/pdf'
  id: '__root__' | '/' | '/decks/$deckId' | '/decks/' | '/api/decks/$deckId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
  ApiDecksDeckIdPdfRoute: typeof ApiDecksDeckIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decks/$deckId/pdf': {
      id: '/api/decks/$deckId/pdf'
      path: '/api/decks/$deckId/pdf'
      fullPath: '/api/decks/$deckId/pdf'
      preLoaderRoute: typeof ApiDecksDeckIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  DecksIndexRoute: DecksIndexRoute,
  ApiDecksDeckIdPdfRoute: ApiDecksDeckIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
